"""English UI labels for Whisper UI.

Generated from the upstream Traditional Chinese label set and reviewed/validated
for key, shape and format-placeholder parity.
"""

from __future__ import annotations

HTML_LANG = "en"

PAGE_UPLOAD = "Upload"
NAV_DASHBOARD = "Dashboard"
NAV_UPLOAD = "Upload"
NAV_JOBS = "Jobs"
NAV_COLLAPSE_SIDEBAR = "Collapse Sidebar"
NAV_EXPAND_SIDEBAR = "Expand Sidebar"
DASHBOARD_HEADER = "Overview"
DASHBOARD_RECENT_SECTION = "Recent Transcriptions"
DASHBOARD_GREETING_MORNING = "Good Morning"
DASHBOARD_GREETING_AFTERNOON = "Good Afternoon"
DASHBOARD_GREETING_EVENING = "Good Evening"
DASHBOARD_GREETING_WITH_NAME = "{greeting}, {name}"
DASHBOARD_GREETING_GUEST = "{greeting}"
DASHBOARD_HERO_IN_FLIGHT = "In Progress"
DASHBOARD_HERO_ETA = "Estimated time remaining: ~{minutes} minutes"
DASHBOARD_HERO_ETA_UNKNOWN = "Progress updating..."
DASHBOARD_STAGE_DOWNLOAD = "Download"
DASHBOARD_STAGE_PREPARE = "Preprocess"
DASHBOARD_STAGE_TRANSCRIBE = "Transcribe"
DASHBOARD_STAGE_DIARIZE = "Diarize"
DASHBOARD_STAGE_CORRECT = "Review"
DASHBOARD_STAGE_EXPORT = "Export"
DASHBOARD_QUICK_ACTION_FILE = "Upload File"
DASHBOARD_QUICK_ACTION_FOLDER = "Upload Folder"
DASHBOARD_QUICK_ACTION_URL = "Paste URL"
DASHBOARD_QUICK_ACTION_FILE_DESC = "Select audio or video files from your device"
DASHBOARD_QUICK_ACTION_FOLDER_DESC = "Transcribe all files in a folder at once"
DASHBOARD_QUICK_ACTION_URL_DESC = "Paste YouTube, X, or Google Drive links to auto-download"
DASHBOARD_ONBOARDING_TITLE = "Welcome to Whisper UI"
DASHBOARD_ONBOARDING_STEP1 = "Upload your first audio or video file"
DASHBOARD_ONBOARDING_STEP2 = "Wait for the system to transcribe and generate results"
DASHBOARD_ONBOARDING_STEP3 = "Download SRT/DOCX files or copy text directly"
DASHBOARD_ONBOARDING_CTA = "Upload Your First File"
DASHBOARD_SPARKLINE_TITLE = "New Files (Last 7 Days)"
UPLOAD_HEADER = "Upload Audio"
UPLOAD_DESCRIPTION = "Upload audio or video files for transcription."
UPLOAD_SUPPORTED_FORMATS = "Supported formats: {formats}"
UPLOAD_CHOOSE_FILE = "Choose File"
UPLOAD_LANGUAGE = "Language"
UPLOAD_MODEL = "Model"
UPLOAD_NUM_SPEAKERS = "Number of Speakers (0 = Auto-detect)"
UPLOAD_ENABLE_DIARIZATION = "Enable Speaker Diarization"
UPLOAD_DIARIZATION_UNAVAILABLE = "Speaker diarization unavailable (HF_TOKEN not set)"
UPLOAD_CONVERT_TRADITIONAL = "Convert Chinese to Traditional Chinese"
UPLOAD_CONVERT_TRADITIONAL_HELP = "Convert Simplified Chinese transcript text to Traditional Chinese (Chinese only)."
UPLOAD_ENABLE_LLM_CORRECTION = "Enable LLM transcript correction"
UPLOAD_LLM_CORRECTION_HELP = (
    "Use an Ollama model to conservatively correct obvious ASR errors in the detected language. "
    "The original text is preserved if correction fails."
)
UPLOAD_LLM_CORRECTION_UNAVAILABLE = "LLM transcript correction is unavailable (OLLAMA_BASE_URL is not configured)."
UPLOAD_START = "Start Transcription"
UPLOAD_ENQUEUE_FAILED = "Error submitting task. Please try again later."
UPLOAD_NO_FILE = "Please upload a file first."
UPLOAD_BATCH_EXCEEDS_LIMIT = "Maximum {limit} files per upload. Currently selected: {count}."
UPLOAD_TAB_FILES = "Select Files"
UPLOAD_TAB_FOLDER = "Select Folder"
UPLOAD_MODE_GROUP = "Upload Mode"
UPLOAD_CHOOSE_FOLDER = "Choose Folder"
UPLOAD_FOLDER_DESCRIPTION = (
    "Select a folder containing audio or video files. Supported formats will be automatically filtered "
    "and batch transcribed."
)
UPLOAD_NO_SUPPORTED_FILES = "No supported formats found in selected files."
UPLOAD_DRAG_DROP = "Drag and drop files here, or click below to select files"
UPLOAD_UPLOADING = "Uploading..."
UPLOAD_FILE_TOO_LARGE = "File '{name}' exceeds size limit ({limit})."
UPLOAD_INVALID_FILE_CONTENT = "File '{name}' is not a valid audio or video file."
UPLOAD_SAVE_FAILED = "Failed to save file '{name}'. Skipped."
UPLOAD_INVALID_LANGUAGE = "Unsupported language: {value}"
UPLOAD_INVALID_MODEL = "Unsupported model: {value}"
UPLOAD_TAB_URL = "Download from URL"
UPLOAD_URL_PLACEHOLDER = "One YouTube video or playlist, X post, or Google Drive link per line..."
UPLOAD_URL_DESCRIPTION = (
    "Enter one or more YouTube videos/playlists, X post URLs, or Google Drive share links (one per line). "
    "The system will automatically download and transcribe them. Playlists will be expanded into multiple "
    "tasks and displayed in batches."
)
UPLOAD_URL_PLAYLIST_NOT_SUPPORTED = (
    "Auto-generated Mix playlists or login-required playlists (Watch Later, Liked Videos) are not supported. "
    "Please provide public playlist URLs or single video links."
)
UPLOAD_URL_PLAYLIST_TOO_LARGE = "The playlist contains {count} videos, exceeding the limit of {limit} per submission."
UPLOAD_URL_PLAYLIST_TOO_LARGE_UNKNOWN = (
    "The playlist contains more than {limit} videos, exceeding the submission limit."
)
UPLOAD_URL_PLAYLIST_EMPTY = "No transcribable videos found in the playlist."
UPLOAD_URL_PLAYLIST_UNAVAILABLE = "Unable to read the playlist. It may be private or deleted."
UPLOAD_URL_PLAYLIST_FETCH_FAILED = "Failed to fetch the playlist. Please try again later."
UPLOAD_URL_DISCLAIMER = (
    "Please confirm you have the right to download the content and comply with relevant terms of service "
    "(including X/Twitter and YouTube). Google Drive files must be set to 'Anyone with the link can view'."
)
UPLOAD_URL_NO_INPUT = "Please enter at least one URL."
UPLOAD_URL_EXCEEDS_LIMIT = "Maximum {limit} URLs per submission. You have entered {count}."
UPLOAD_URL_ALL_INVALID = "All entered URLs are invalid. Please verify they are YouTube, X, or Google Drive links."
UPLOAD_PRESET_SECTION = "Presets"
UPLOAD_PRESET_MEETING = "Meeting"
UPLOAD_PRESET_PODCAST = "Podcast"
UPLOAD_PRESET_INTERVIEW = "Interview"
UPLOAD_PRESET_LECTURE = "Lecture"
UPLOAD_PRESET_MEETING_DESC = "Auto-detect language, multiple speakers, diarization and LLM correction enabled"
UPLOAD_PRESET_PODCAST_DESC = "Auto-detect language, 2 speakers, LLM correction enabled"
UPLOAD_PRESET_INTERVIEW_DESC = "Auto-detect language, 2 speakers, diarization and LLM correction enabled"
UPLOAD_PRESET_LECTURE_DESC = "Auto-detect language, single speaker, LLM correction enabled"
UPLOAD_PRESET_CUSTOM = "Customizing..."
UPLOAD_SECTION_BASIC = "Basic Settings"
UPLOAD_SECTION_ADVANCED = "Advanced Settings"
UPLOAD_ADVANCED_ENABLED_COUNT = "{count} advanced settings enabled"
UPLOAD_ADVANCED_TOGGLE_EXPAND = "Expand Advanced Settings"
UPLOAD_ADVANCED_TOGGLE_COLLAPSE = "Collapse Advanced Settings"
UPLOAD_SUBMIT_STATUS_FILES = "Preparing to transcribe {count} files"
UPLOAD_SUBMIT_STATUS_URLS = "Preparing to transcribe {count} URLs"
UPLOAD_SUBMIT_STATUS_EMPTY = "No source selected yet"
UPLOAD_INFOTIP_LABEL = "View instructions"
JOBS_HEADER = "Jobs"
JOBS_EMPTY = "No jobs yet. Go to **Upload** to submit files."
JOBS_VIEW = "View"
JOBS_WAITING = "Waiting..."
JOBS_ERROR = "Error: {error}"
JOBS_QUALITY_WARNING_BADGE = "Quality warning"
JOBS_RETRY = "Retry"
JOBS_RETRY_CONFIRM = "Are you sure you want to retry this job?"
JOBS_RETRY_CONFIRM_BUTTON = "Confirm retry"
JOBS_DELETE = "Delete"
JOBS_DELETE_CONFIRM = "Are you sure you want to delete this job? This action cannot be undone."
JOBS_DELETE_CONFIRM_BUTTON = "Confirm delete"
JOBS_RE_TRANSCRIBE = "Re-transcribe"
JOBS_RE_TRANSCRIBE_TITLE = "Re-transcribe with different settings"
JOBS_RE_TRANSCRIBE_DESC = (
    "Keeps the original transcript and creates a new version with the new settings without re-uploading audio."
)
JOBS_RE_TRANSCRIBE_SUBMIT = "Create new version"
JOBS_RE_TRANSCRIBE_SUCCESS = "New version created and transcription started"
JOBS_RE_TRANSCRIBE_FAILED = "Re-transcription failed. Please try again later."
JOBS_RE_TRANSCRIBE_SOURCE_GONE = "Original audio has been cleaned up. Cannot re-transcribe. Please re-upload."
JOBS_VERSION_BADGE = "Re-transcribed version"
JOBS_BATCH_LABEL = "Batch upload ({count} files)"
JOBS_BATCH_LABEL_TITLED = "{title} ({count} videos)"
JOBS_BATCH_PROGRESS = "{completed}/{total} completed"
JOBS_BATCH_TOGGLE_LABEL = "Expand or collapse this batch"
JOBS_BATCH_RETRY_ALL = "Retry all"
JOBS_BATCH_RETRY_ALL_CONFIRM = "Are you sure you want to retry all failed jobs in this batch?"
JOBS_BATCH_RETRY_ALL_CONFIRM_BUTTON = "Confirm retry all"
JOBS_BATCH_DELETE_ALL = "Delete all"
JOBS_BATCH_DELETE_ALL_CONFIRM = "Are you sure you want to delete all jobs in this batch? This action cannot be undone."
JOBS_BATCH_DELETE_ALL_CONFIRM_BUTTON = "Confirm delete all"
JOBS_BATCH_DOWNLOAD = "Batch download"
JOBS_BATCH_DOWNLOAD_FORMAT = "Select export format"
JOBS_BATCH_DOWNLOAD_BUTTON = "Download ZIP"
JOBS_FILTER_ALL = "All"
JOBS_EMPTY_FILTERED = "No tasks match the filter."
JOBS_PAGE_INFO = "Page {current} of {total} ({count} tasks)"
JOBS_PAGE_PREV = "Previous"
JOBS_PAGE_NEXT = "Next"
JOBS_STALE_ERROR = "Task timed out or worker terminated abnormally"
JOBS_TIMEOUT_ERROR = (
    "Task execution exceeded the limit ({seconds}s). Audio may be too long or device busy. "
    "Adjust JOB_TIMEOUT_MAX and retry."
)
JOBS_STAGE_FAILED_DOWNLOAD = "Media download failed. Please verify the source URL and retry."
JOBS_STAGE_FAILED_PREPROCESS = "Audio preprocessing failed. File may be corrupted or unsupported format."
JOBS_STAGE_FAILED_TRANSCRIPTION = "Transcription failed. Please try again later."
JOBS_STAGE_FAILED_ALIGNMENT = "Word alignment failed. Please try again later."
JOBS_STAGE_FAILED_DIARIZATION = "Speaker diarization failed. Please try again later."
JOBS_STAGE_FAILED_GENERIC = "Task processing failed. Please try again later."
JOBS_SEARCH_PLACEHOLDER = "Search file name or URL..."
JOBS_INLINE_EXPORT = "Export"
JOBS_SELECT_ROW = "Select this task"
JOBS_BULK_SELECTED = "{count} selected"
JOBS_BULK_CLEAR_SELECTION = "Clear selection"
JOBS_BULK_RETRY = "Batch retry"
JOBS_BULK_DELETE = "Batch delete"
JOBS_BULK_EXPORT = "Batch export"
JOBS_BULK_CONFIRM_RETRY = "Retry the selected {count} tasks?"
JOBS_BULK_CONFIRM_DELETE = "Delete the selected {count} tasks? This action cannot be undone."
JOBS_BULK_SUCCESS = "Processed {count} tasks"
JOBS_BULK_PARTIAL = "Processed {ok} tasks, {failed} failed"
JOBS_BULK_RETRY_HINT = "Select at least one failed task"
JOBS_BULK_EXPORT_HINT = "Select at least one completed task"
VIEWER_NOT_FOUND = "Task not found."
VIEWER_NOT_COMPLETED = "Task is not yet complete. Status: {status}"
VIEWER_RESULT_NOT_FOUND = "Result file not found."
VIEWER_TRANSCRIPT_TITLE = "Transcript: {name}"
VIEWER_METADATA = "Duration: {minutes}m {seconds}s | Segments: {segments} | Language: {language}"
VIEWER_NO_SEGMENTS = "No segments found in the transcript."
VIEWER_SEARCH_PLACEHOLDER = "Filter by keyword..."
VIEWER_SEARCH_NO_RESULTS = "No matching segments found."
VIEWER_SEARCH_DISABLED = (
    "Too many segments ({count}), real-time search disabled to prevent browser lag. "
    "Use your browser's built-in search (Ctrl/Cmd + F) or export as TXT to search."
)
VIEWER_EMPTY_STATE = "Select a completed task from above to view the transcript."
VIEWER_COPY = "Copy Full Text"
VIEWER_COPIED = "Copied"
VIEWER_EXPORT_TOOLTIPS: dict[str, str] = {
    "srt": "SubRip Subtitle Format",
    "vtt": "WebVTT Subtitle Format",
    "txt": "Plain Text Format",
    "json": "JSON Structured Data",
    "docx": "Microsoft Word Document",
}
VIEWER_BACK_TO_JOBS = "Back to Jobs"
VIEWER_COPY_SEGMENT = "Copy Segment"
VIEWER_SOURCE_URL = "Source Video"
VIEWER_DOWNLOAD_MEDIA = "Download Media"
VIEWER_SEGMENT_COPIED = "Segment Copied"
VIEWER_SHORTCUTS_TITLE = "Keyboard Shortcuts"
VIEWER_SHORTCUTS_FOCUS_SEARCH = "Focus Search"
VIEWER_SHORTCUTS_NAV = "Previous/Next Segment"
VIEWER_SHORTCUTS_COPY = "Copy Current Segment"
VIEWER_SHORTCUTS_CLEAR = "Clear Search"
VIEWER_SHORTCUTS_PLAY_PAUSE = "Play/Pause"
VIEWER_SHORTCUTS_SEEK = "Rewind/Forward 5s"
VIEWER_PLAYER_UNAVAILABLE = "Your browser does not support this media format."
VIEWER_SEEK_TO = "Jump to Time"
VIEWER_SHARE = "Share"
VIEWER_SHARE_LINK_CREATED = "Share Link Created"
VIEWER_SHARE_LINK_LABEL = "Share Link"
VIEWER_SHARE_COPY_LINK = "Copy Link"
VIEWER_SHARE_LINK_COPIED = "Link Copied"
VIEWER_SHARE_REVOKE = "Revoke Share"
VIEWER_SHARE_REVOKE_CONFIRM = "Are you sure you want to revoke the share? Shared links will become invalid."
VIEWER_SHARE_REVOKE_CONFIRM_BUTTON = "Confirm Revoke"
VIEWER_SHARED_TITLE = "Shared Transcript: {name}"
VIEWER_SHARED_BADGE = "Shared Transcript"
TOAST_UPLOAD_SUCCESS = "Submitted {count} tasks"
TOAST_URL_SKIPPED = ", skipped {count} invalid URLs"
TOAST_FILE_SKIPPED = ", skipped {count} invalid files"
TOAST_URL_DEDUPED = ", removed {count} duplicate URLs"
TOAST_UPLOAD_FAILED = ", failed to submit {count} tasks"
TOAST_NETWORK_ERROR = "Network error, please try again later"
TOAST_ACTION_FAILED = "Action failed, please try again later"
THEME_TOGGLE_LIGHT = "Light Mode"
THEME_TOGGLE_DARK = "Dark Mode"
DIALOG_CANCEL = "Cancel"
DIALOG_CONFIRM = "Confirm"
AUTH_LOGIN_HEADER = "Login"
AUTH_LOGIN_DESCRIPTION = "Enter your username and password."
AUTH_USERNAME = "Username"
AUTH_USERNAME_HELP = "3-32 characters, letters, numbers, underscores, and hyphens only"
AUTH_PASSWORD = "Password"
AUTH_PASSWORD_HELP = "At least 8 characters"
AUTH_LOGIN_BUTTON = "Login"
AUTH_LOGOUT_BUTTON = "Logout"
AUTH_REGISTER_HEADER = "Register Account"
AUTH_REGISTER_DESCRIPTION = "Create a new account to get started with Whisper UI."
AUTH_REGISTER_BUTTON = "Create Account"
AUTH_BOOTSTRAP_HEADER = "Create Admin Account"
AUTH_BOOTSTRAP_DESCRIPTION = (
    "On first use, create the first admin account. This account will have permissions to manage users "
    "and view all tasks."
)
AUTH_BOOTSTRAP_WARNING = "You are creating the system's first admin account. Please keep your login credentials safe."
AUTH_PASSWORD_SHOW = "Show Password"
AUTH_PASSWORD_HIDE = "Hide Password"
AUTH_LOGIN_FAILED = "Invalid username or password, please try again."
AUTH_ACCOUNT_INACTIVE = "This account is inactive. Please contact the administrator."
AUTH_USERNAME_TAKEN = "This username is already taken. Please choose another."
AUTH_REGISTER_UNAVAILABLE = "Registration failed. Please try a different name or later."
AUTH_USERNAME_INVALID = "Invalid username format (3-32 characters, letters, numbers, underscores, hyphens)."
AUTH_PASSWORD_TOO_SHORT = "Password must be at least 8 characters."
AUTH_LOGIN_LINK = "Already have an account? Sign in"
AUTH_REGISTER_LINK = "Don't have an account? Sign up"
AUTH_SIGNED_IN_AS = "Signed in as: {username}"
AUTH_ADMIN_BADGE = "Admin"
AUTH_RATE_LIMITED = "Too many attempts. Please try again in {minutes} minutes."
AUTH_REGISTER_RATE_LIMITED = "Too many registration attempts. Please try again later."
ADMIN_USERS_HEADER = "User Management"
ADMIN_USERS_DESCRIPTION = (
    "Add, deactivate, change permissions, or reset passwords. "
    "Deactivation immediately invalidates all sessions for that user."
)
ADMIN_USER_COL_USERNAME = "Username"
ADMIN_USER_COL_ROLE = "Role"
ADMIN_USER_COL_STATUS = "Status"
ADMIN_USER_COL_CREATED = "Created"
ADMIN_USER_COL_JOBS = "Jobs"
ADMIN_USER_COL_ACTIONS = "Actions"
ADMIN_USER_ROLE_ADMIN = "Admin"
ADMIN_USER_ROLE_USER = "User"
ADMIN_USER_STATUS_ACTIVE = "Active"
ADMIN_USER_STATUS_INACTIVE = "Inactive"
ADMIN_ACTION_DEACTIVATE = "Deactivate"
ADMIN_ACTION_ACTIVATE = "Activate"
ADMIN_ACTION_PROMOTE = "Promote to Admin"
ADMIN_ACTION_DEMOTE = "Demote from Admin"
ADMIN_ACTION_RESET_PASSWORD = "Reset Password"
ADMIN_ADD_USER_HEADER = "Add User"
ADMIN_ADD_USER_SUBMIT = "Create Account"
ADMIN_RESET_PASSWORD_HEADER = "Reset Password for {username}"
ADMIN_RESET_PASSWORD_SUBMIT = "Confirm Reset"
ADMIN_LAST_ADMIN_ERROR = "System requires at least one active admin. This action cannot be performed."
ADMIN_SELF_ACTION_ERROR = "Cannot perform this action on yourself."
ADMIN_USER_NOT_FOUND_ERROR = "User not found, possibly deleted."
ADMIN_JOBS_HEADER = "All Jobs"
ADMIN_JOBS_DESCRIPTION = "Displays all jobs in the system (including ownerless historical data)."
ADMIN_JOBS_OWNER_UNKNOWN = "(No Owner)"
ADMIN_NAV_USERS = "Users"
ADMIN_NAV_JOBS = "All Jobs"
STATUS_LABELS: dict[str, str] = {
    "pending": "Pending",
    "queued": "Queued",
    "processing": "Processing",
    "completed": "Completed",
    "failed": "Failed",
}

# -- Generic time / self labels --
TIME_JUST_NOW = "just now"
TIME_MINUTES_AGO = "{minutes} minutes ago"
TIME_HOURS_AGO = "{hours} hours ago"
TIME_YESTERDAY = "yesterday"
TIME_DAYS_AGO = "{days} days ago"
DASHBOARD_DURATION_SHORT = "{minutes}m {seconds}s"
ADMIN_SELF_BADGE = "You"
